### PR TITLE
Update ci.yml

### PR DESCRIPTION
**Pull request by dlfivefifty**

### CODE REVIEW

**Comment by andreasnoack** [comment]
There are many of the changes here I don't understand. I hadn't realized that lts had been disabled in https://github.com/JuliaLinearAlgebra/GenericLinearAlgebra.jl/pull/85 but, except for that one, why are the changes needed? It's deliberate that I don't test on Mac and Windows since there are no binary dependencies so it doesn't seem worth the extra CI time.

**Comment by dlfivefifty** [comment]
I just copied CI from another repository (I think FillArrays.jl) which @jishnub made changes to...

I can revert the ci.yml and just add a test for `lts`.

For reasons that are beyond my comprehension the tests on ubuntu/macos are using test files from a different branch which makes no sense to me so maybe reverting the CI will avoid this issue...

**Comment by dlfivefifty** [comment]
Oh sorry! I didn't see that you merged the other PR. That's why the tests are failing

**Comment by dlfivefifty** [comment]
I think we can ignore the codecov failure since it relates to 1.6 specific code

**Review by andreasnoack — APPROVED** [review]

**Comment by andreasnoack** [comment]
Thanks for the fixes

**Pull request merged**
