### PR TITLE
Sort eigenvalues consistently with Base

### PR DESCRIPTION
**Pull request by ericphanson**
Fixes https://github.com/JuliaLinearAlgebra/GenericLinearAlgebra.jl/issues/47

Uses the approach mentioned in https://github.com/JuliaLinearAlgebra/GenericLinearAlgebra.jl/issues/47#issuecomment-527685147

Edit: this PR went through a couple iterations; the final changes are described in https://github.com/JuliaLinearAlgebra/GenericLinearAlgebra.jl/pull/56#issuecomment-531952996

### CODE REVIEW

**Comment by ericphanson** [comment]
I realized that the eigenvalues in `eigenSelfAdjoint` already are sorted, so the sorting behavior should be the same as Base LinearAlgebra on pre-1.2 anyway. However, that's not the case in my test problem which is what led me here. I think the difference is actually

https://github.com/JuliaLang/julia/blob/4966ed4f5d6d73169f302d10611aa97a3bd87172/stdlib/LinearAlgebra/src/eigen.jl#L292

and

https://github.com/JuliaLang/julia/blob/4966ed4f5d6d73169f302d10611aa97a3bd87172/stdlib/LinearAlgebra/src/eigen.jl#L297

These redirections do not appear in GenericLinearAlgebra, and they cause a difference the sorting of eigenvalues for matrices `A` such that `ishermitian(A)==true`, but which are not of type `Hermitian`.

So maybe I should put the `eigenGeneral` functionality behind a `VERSION < ...` check, and also add the redirections. That would eliminate the code duplication from Base (for the `eigsortby` stuff).

**Comment by ericphanson** [comment]
Ok, I cleaned up the PR a bit, since extraneous whitespace changes had crept in; I'm done now. To summarize:

* On Julia 1.0+, in `eigvals!`, LinearAlgebra checks for `ishermitian(A)==true`; in that case, it wraps the matrix in the `Hermitian` wrapper and calls the `eigvals!` method on that. This causes matrices `A` that are not wrapped in `Hermitian` but have `ishermitian(A)==true` to have their eigenvalues sorted. GenericLinearAlgebra lacked this redirect, which caused mismatch in sorting behavior on 1.0+ in that case.
* In Julia 1.2, sorting of eigenvalues in the general case was introduced. GenericLinearAlgebra did not also introduce this, causing a mismatch in sorting behavior in that case, on 1.2+.

This PR fixes both sorting mismatches by matching the Base behavior, using a `VERSION` check in the second case.

Julia also wraps `issymmetric` matrices, but since only specialized methods are implemented in GenericLinearAlgebra for the `Hermitian` wrappers, I did not add that redirect (since it would yield errors unless `::Symmetric` methods were also added.

**Comment by andreasnoack** [comment]
Great. Thanks for fixing this.

**Comment by ericphanson** [comment]
Could a release be tagged with this change? It would let us use the `lambdamax` and `lambdamin` atoms from Convex.jl with the high-precision SDP solvers from https://github.com/ericphanson/SDPAFamily.jl.

**Comment by andreasnoack** [comment]
https://github.com/JuliaRegistries/General/pull/3700

**Comment by ericphanson** [comment]
Thanks very much!

**Pull request merged**
